import streamlit as st


def show_demo():

    if "demo_progress" not in st.session_state:
        st.session_state.demo_progress = 0.1

    st.title("🎬 AgenticAI Demo")

    st.progress(st.session_state.demo_progress)

    st.info("This is a demo workflow showing how AgenticAI converts leads into proposals.")

    col1, col2, col3 = st.columns([1,1,1])

    with col1:
        st.markdown("## Demo Lead")

        st.write("Company: **Acme Bank**")
        st.write("Industry: **BFSI**")
        st.write("Contact: **John Smith**")

        st.markdown("->>> Create Campaign")

    with col2:
        st.markdown("## Campaign")

        st.write("Campaign: AI Customer Analytics")
        st.write("Collateral: Corporate Overview PPT")

        if st.button("Send Outreach Email"):

            st.success("Reachout Sent Successfully!")
            st.write("Status → Sent")
            st.session_state.demo_progress = 0.4

        st.markdown("->>> Create Opportunity")

    with col3:
        st.markdown("## Opportunity")

        if st.button("Create Opportunity"):

            st.success("Opportunity Created")
            st.write("Value: $50,000")
            st.session_state.demo_progress = 0.6

        st.markdown("->> Sync to CRM")

    col1, col2, col3 = st.columns([1,1,1])

    with col1:
        st.markdown("## CRM Sync")

        if st.button("Sync to CRM"):

            st.success("Synced to CRM")
            st.write("CRM ID: CRM-10245")
            st.session_state.demo_progress = 0.7

        st.markdown("->>> Generate Proposal")

    with col2:
        st.markdown("## Proposal")

        if st.button("Generate Proposal"):

            st.success("Proposal Generated")
            st.session_state.demo_progress = 1.0

            st.download_button(
                "Download Demo Proposal",
                "This is a demo proposal generated by AgentiAI.",
                file_name="demo_proposal.txt"
            )

        st.markdown("->> End of Demo")
    with col3:
        if st.button("⬅ Back to Landing Page"):
            st.session_state.mode = "landing"
            st.session_state.demo_progress = 0.1
            st.rerun()